<a href="https://colab.research.google.com/github/alra-code/alura-aprendendo-a-fazer-ETL/blob/main/Desafio_transformacao_manipulacao_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##*Desafio 1: trabalhando em outros contextos*

Fontes: https://cdn3.gnarususercontent.com.br/2928-transformacao-manipulacao-dados/dados_vendas_clientes.json

https://cdn3.gnarususercontent.com.br/2928-transformacao-manipulacao-dados/dados_locacao_imoveis.json

#**Tratando os dados Vendas clientes**

In [ ]:
#importação da biblioteca
import pandas as pd

#leitura do arquivo
dados_vendas_clientes = pd.read_json('/content/dados_vendas_clientes.json')

#visualização do dataframe
dados_vendas_clientes

                                        dados_vendas
0  {'Data de venda': '06/06/2022', 'Cliente': ['@...
1  {'Data de venda': '07/06/2022', 'Cliente': ['I...
2  {'Data de venda': '08/06/2022', 'Cliente': ['I...
3  {'Data de venda': '09/06/2022', 'Cliente': ['J...
4  {'Data de venda': '10/06/2022', 'Cliente': ['M...

In [ ]:
#aplicação do json_normalize
dados_vendas_clientes = pd.json_normalize(dados_vendas_clientes['dados_vendas'])

#visualização do dataframe
dados_vendas_clientes

,Data de venda,Cliente,Valor da compra
0,06/06/2022,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...","[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,07/06/2022,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...","[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,08/06/2022,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...","[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"
3,09/06/2022,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...","[R$ 390,3, R$ 759,16, R$ 334,47, R$ 678,78]"
4,10/06/2022,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...","[R$ 314,24, R$ 311,15, R$ 899,16, R$ 885,24]"

In [ ]:
# Coletar os valores das colunas e verificar
colunas = list(dados_vendas_clientes.columns)
colunas

['Data de venda', 'Cliente', 'Valor da compra']

In [ ]:
# Destrinchar as listas com explode
dados_vendas_clientes = dados_vendas_clientes.explode(colunas[1:])

In [ ]:
# Resetar os index das linhas
dados_vendas_clientes.reset_index(drop=True,inplace=True)

In [ ]:
# Observar o DataFrame
dados_vendas_clientes

   Data de venda             Cliente Valor da compra
0     06/06/2022     @ANA _LUCIA 321        R$ 836,5
1     06/06/2022  DieGO ARMANDIU 210       R$ 573,33
2     06/06/2022  DieGO ARMANDIU 210        R$ 392,8
3     06/06/2022  DieGO ARMANDIU 210       R$ 512,34
4     07/06/2022  Isabely JOanes 738       R$ 825,31
5     07/06/2022  Isabely JOanes 738       R$ 168,07
6     07/06/2022  Isabely JOanes 738       R$ 339,18
7     07/06/2022  Isabely JOanes 738       R$ 314,69
8     08/06/2022  Isabely JOanes 738       R$ 682,05
9     08/06/2022    JOãO Gabriel 671       R$ 386,34
10    08/06/2022  Julya meireles 914       R$ 622,65
11    08/06/2022  Julya meireles 914       R$ 630,79
12    09/06/2022  Julya meireles 914        R$ 390,3
13    09/06/2022     MaRIA Julia 444       R$ 759,16
14    09/06/2022     MaRIA Julia 444       R$ 334,47
15    09/06/2022     MaRIA Julia 444       R$ 678,78
16    10/06/2022     MaRIA Julia 444       R$ 314,24
17    10/06/2022     PEDRO PASCO 812       R$ 311,15
18    10/06/2022    Paulo castro 481       R$ 899,16
19    10/06/2022   Thiago fritzz 883       R$ 885,24

In [ ]:
# Verificar os tipos de dados com info
dados_vendas_clientes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     object
dtypes: object(3)
memory usage: 612.0+ bytes

In [ ]:
# A coluna numérica é a 'Valor da compra'
dados_vendas_clientes['Valor da compra']

0      R$ 836,5
1     R$ 573,33
2      R$ 392,8
3     R$ 512,34
4     R$ 825,31
5     R$ 168,07
6     R$ 339,18
7     R$ 314,69
8     R$ 682,05
9     R$ 386,34
10    R$ 622,65
11    R$ 630,79
12     R$ 390,3
13    R$ 759,16
14    R$ 334,47
15    R$ 678,78
16    R$ 314,24
17    R$ 311,15
18    R$ 899,16
19    R$ 885,24
Name: Valor da compra, dtype: object

In [ ]:
# Remover os textos presentes na base
# Trocar as vírgulas separadoras do decimal por ponto
dados_vendas_clientes['Valor da compra'] = dados_vendas_clientes['Valor da compra'].apply(lambda x: x.replace('R$ ', '').replace(',','.').strip())

In [ ]:
# Alterar os tipo de dado para float
dados_vendas_clientes['Valor da compra'] = dados_vendas_clientes['Valor da compra'].astype(np.float64)

In [ ]:
# Verificar a transformação
dados_vendas_clientes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     float64
dtypes: float64(1), object(2)
memory usage: 612.0+ bytes

In [ ]:
dados_vendas_clientes

   Data de venda             Cliente  Valor da compra
0     06/06/2022     @ANA _LUCIA 321           836.50
1     06/06/2022  DieGO ARMANDIU 210           573.33
2     06/06/2022  DieGO ARMANDIU 210           392.80
3     06/06/2022  DieGO ARMANDIU 210           512.34
4     07/06/2022  Isabely JOanes 738           825.31
5     07/06/2022  Isabely JOanes 738           168.07
6     07/06/2022  Isabely JOanes 738           339.18
7     07/06/2022  Isabely JOanes 738           314.69
8     08/06/2022  Isabely JOanes 738           682.05
9     08/06/2022    JOãO Gabriel 671           386.34
10    08/06/2022  Julya meireles 914           622.65
11    08/06/2022  Julya meireles 914           630.79
12    09/06/2022  Julya meireles 914           390.30
13    09/06/2022     MaRIA Julia 444           759.16
14    09/06/2022     MaRIA Julia 444           334.47
15    09/06/2022     MaRIA Julia 444           678.78
16    10/06/2022     MaRIA Julia 444           314.24
17    10/06/2022     PEDRO PASCO 812           311.15
18    10/06/2022    Paulo castro 481           899.16
19    10/06/2022   Thiago fritzz 883           885.24

In [ ]:
colunas = list(dados_vendas_clientes.columns)
colunas

['Data de venda', 'Cliente', 'Valor da compra']

In [ ]:
# Transformar os textos de Cliente para texto em minúsculo
dados_vendas_clientes['Cliente'] = dados_vendas_clientes['Cliente'].str.lower()

In [ ]:
# Verificar o resultado
dados_vendas_clientes.head()

  Data de venda             Cliente  Valor da compra
0    06/06/2022     @ana _lucia 321           836.50
1    06/06/2022  diego armandiu 210           573.33
2    06/06/2022  diego armandiu 210           392.80
3    06/06/2022  diego armandiu 210           512.34
4    07/06/2022  isabely joanes 738           825.31

In [ ]:
# Tudo que satisfaz o regex é apagado
dados_vendas_clientes['Cliente'].str.replace('[^a-z ]', '', regex=True)

0          ana lucia
1     diego armandiu
2     diego armandiu
3     diego armandiu
4     isabely joanes
5     isabely joanes
6     isabely joanes
7     isabely joanes
8     isabely joanes
9        joo gabriel
10    julya meireles
11    julya meireles
12    julya meireles
13       maria julia
14       maria julia
15       maria julia
16       maria julia
17       pedro pasco
18      paulo castro
19     thiago fritzz
Name: Cliente, dtype: object

In [ ]:
# Atribuindo o resultado a coluna Cliente
dados_vendas_clientes['Cliente'] = dados_vendas_clientes['Cliente'].str.replace('[^a-z ]', '', regex=True).str.strip()

In [ ]:
# Visualizar o resultado final
dados_vendas_clientes.head()

  Data de venda         Cliente  Valor da compra
0    06/06/2022       ana lucia           836.50
1    06/06/2022  diego armandiu           573.33
2    06/06/2022  diego armandiu           392.80
3    06/06/2022  diego armandiu           512.34
4    07/06/2022  isabely joanes           825.31

In [ ]:
# Transformando o tipo datetime para como DD/MM/AAAA ('%d/%m/%Y')
dados_vendas_clientes['Data de venda'] = pd.to_datetime(dados_vendas_clientes['Data de venda'], format='%d/%m/%Y')

In [ ]:
#Visualizando o resultado
dados_vendas_clientes

   Data de venda         Cliente  Valor da compra
0     2022-06-06       ana lucia           836.50
1     2022-06-06  diego armandiu           573.33
2     2022-06-06  diego armandiu           392.80
3     2022-06-06  diego armandiu           512.34
4     2022-06-07  isabely joanes           825.31
5     2022-06-07  isabely joanes           168.07
6     2022-06-07  isabely joanes           339.18
7     2022-06-07  isabely joanes           314.69
8     2022-06-08  isabely joanes           682.05
9     2022-06-08     joo gabriel           386.34
10    2022-06-08  julya meireles           622.65
11    2022-06-08  julya meireles           630.79
12    2022-06-09  julya meireles           390.30
13    2022-06-09     maria julia           759.16
14    2022-06-09     maria julia           334.47
15    2022-06-09     maria julia           678.78
16    2022-06-10     maria julia           314.24
17    2022-06-10     pedro pasco           311.15
18    2022-06-10    paulo castro           899.16
19    2022-06-10   thiago fritzz           885.24

In [ ]:
# Calcular o total arrecadado em compras por cada cliente
total_compras = dados_vendas_clientes.groupby(['Cliente'])['Valor da compra'].sum()

In [ ]:
# Visualizar o resultado
total_compras

Cliente
ana lucia          836.50
diego armandiu    1478.47
isabely joanes    2329.30
joo gabriel        386.34
julya meireles    1643.74
maria julia       2086.65
paulo castro       899.16
pedro pasco        311.15
thiago fritzz      885.24
Name: Valor da compra, dtype: float64

In [135]:
dados_vendas_clientes.head()

  Data de venda         Cliente  Valor da compra
0    2022-06-06       ana lucia           836.50
1    2022-06-06  diego armandiu           573.33
2    2022-06-06  diego armandiu           392.80
3    2022-06-06  diego armandiu           512.34
4    2022-06-07  isabely joanes           825.31

In [139]:
dados_vendas_clientes.to_csv('dados_tratados.csv', index=False)

In [140]:
df = pd.read_csv('/content/dados_tratados.csv')
df

   Data de venda         Cliente  Valor da compra
0     2022-06-06       ana lucia           836.50
1     2022-06-06  diego armandiu           573.33
2     2022-06-06  diego armandiu           392.80
3     2022-06-06  diego armandiu           512.34
4     2022-06-07  isabely joanes           825.31
5     2022-06-07  isabely joanes           168.07
6     2022-06-07  isabely joanes           339.18
7     2022-06-07  isabely joanes           314.69
8     2022-06-08  isabely joanes           682.05
9     2022-06-08     joo gabriel           386.34
10    2022-06-08  julya meireles           622.65
11    2022-06-08  julya meireles           630.79
12    2022-06-09  julya meireles           390.30
13    2022-06-09     maria julia           759.16
14    2022-06-09     maria julia           334.47
15    2022-06-09     maria julia           678.78
16    2022-06-10     maria julia           314.24
17    2022-06-10     pedro pasco           311.15
18    2022-06-10    paulo castro           899.16
19    2022-06-10   thiago fritzz           885.24

#**Tratamento dos dados Locação Imoveis**

In [ ]:
#leitura do arquivo
dados2 = pd.read_json('/content/dados_locacao_imoveis.json')

#visualização do dataframe
dados2

                                        dados_locacao
0   {'apartamento': 'A101 (blocoAP)', 'datas_combi...
1   {'apartamento': 'A102 (blocoAP)', 'datas_combi...
2   {'apartamento': 'B201 (blocoAP)', 'datas_combi...
3   {'apartamento': 'B202 (blocoAP)', 'datas_combi...
4   {'apartamento': 'C301 (blocoAP)', 'datas_combi...
5   {'apartamento': 'C302 (blocoAP)', 'datas_combi...
6   {'apartamento': 'D401 (blocoAP)', 'datas_combi...
7   {'apartamento': 'D402 (blocoAP)', 'datas_combi...
8   {'apartamento': 'E501 (blocoAP)', 'datas_combi...
9   {'apartamento': 'E502 (blocoAP)', 'datas_combi...
10  {'apartamento': 'F601 (blocoAP)', 'datas_combi...
11  {'apartamento': 'F602 (blocoAP)', 'datas_combi...
12  {'apartamento': 'G701 (blocoAP)', 'datas_combi...
13  {'apartamento': 'G702 (blocoAP)', 'datas_combi...
14  {'apartamento': 'H801 (blocoAP)', 'datas_combi...

In [ ]:
#aplicação do json_normalize
dados2 = pd.json_normalize(dados2['dados_locacao'])

#visualização do dataframe
dados2

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),"[01/06/2022, 01/07/2022]","[05/06/2022, 03/07/2022]","[$ 1000,0 reais, $ 2500,0 reais]"
1,A102 (blocoAP),"[02/06/2022, 02/07/2022]","[02/06/2022, 06/07/2022]","[$ 1100,0 reais, $ 2600,0 reais]"
2,B201 (blocoAP),"[03/06/2022, 03/07/2022]","[07/06/2022, 03/07/2022]","[$ 1200,0 reais, $ 2700,0 reais]"
3,B202 (blocoAP),"[04/06/2022, 04/07/2022]","[07/06/2022, 05/07/2022]","[$ 1300,0 reais, $ 2800,0 reais]"
4,C301 (blocoAP),"[05/06/2022, 05/07/2022]","[10/06/2022, 09/07/2022]","[$ 1400,0 reais, $ 2900,0 reais]"
5,C302 (blocoAP),"[06/06/2022, 06/07/2022]","[08/06/2022, 12/07/2022]","[$ 1500,0 reais, $ 1200,0 reais]"
6,D401 (blocoAP),"[07/06/2022, 07/07/2022]","[07/06/2022, 09/07/2022]","[$ 1600,0 reais, $ 1300,0 reais]"
7,D402 (blocoAP),"[08/06/2022, 08/07/2022]","[10/06/2022, 14/07/2022]","[$ 1700,0 reais, $ 1400,0 reais]"
8,E501 (blocoAP),"[09/06/2022, 09/07/2022]","[10/06/2022, 09/07/2022]","[$ 1800,0 reais, $ 1500,0 reais]"
9,E502 (blocoAP),"[10/06/2022, 10/07/2022]","[16/06/2022, 12/07/2022]","[$ 1900,0 reais, $ 1600,0 reais]"
10,F601 (blocoAP),"[11/06/2022, 11/07/2022]","[17/06/2022, 13/07/2022]","[$ 2000,0 reais, $ 1000,0 reais]"
11,F602 (blocoAP),"[12/06/2022, 12/07/2022]","[15/06/2022, 12/07/2022]","[$ 2100,0 reais, $ 1100,0 reais]"
12,G701 (blocoAP),"[13/06/2022, 13/07/2022]","[19/06/2022, 20/07/2022]","[$ 2200,0 reais, $ 1200,0 reais]"
13,G702 (blocoAP),"[14/06/2022, 14/07/2022]","[15/06/2022, 17/07/2022]","[$ 2300,0 reais, $ 2100,0 reais]"
14,H801 (blocoAP),"[15/06/2022, 15/07/2022]","[18/06/2022, 16/07/2022]","[$ 2400,0 reais, $ 2200,0 reais]"

In [ ]:
# Coletar os valores das colunas e verificar
colunas = list(dados2.columns)
colunas

['apartamento',
 'datas_combinadas_pagamento',
 'datas_de_pagamento',
 'valor_aluguel']

In [ ]:
# Destrinchar as listas com explode
dados2 = dados2.explode(colunas[1:])
# Resetar os index das linhas
dados2.reset_index(drop=True,inplace=True)
# Observar o DataFrame
dados2

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,"$ 1000,0 reais"
1,A101 (blocoAP),01/07/2022,03/07/2022,"$ 2500,0 reais"
2,A102 (blocoAP),02/06/2022,02/06/2022,"$ 1100,0 reais"
3,A102 (blocoAP),02/07/2022,06/07/2022,"$ 2600,0 reais"
4,B201 (blocoAP),03/06/2022,07/06/2022,"$ 1200,0 reais"
5,B201 (blocoAP),03/07/2022,03/07/2022,"$ 2700,0 reais"
6,B202 (blocoAP),04/06/2022,07/06/2022,"$ 1300,0 reais"
7,B202 (blocoAP),04/07/2022,05/07/2022,"$ 2800,0 reais"
8,C301 (blocoAP),05/06/2022,10/06/2022,"$ 1400,0 reais"
9,C301 (blocoAP),05/07/2022,09/07/2022,"$ 2900,0 reais"
10,C302 (blocoAP),06/06/2022,08/06/2022,"$ 1500,0 reais"
11,C302 (blocoAP),06/07/2022,12/07/2022,"$ 1200,0 reais"
12,D401 (blocoAP),07/06/2022,07/06/2022,"$ 1600,0 reais"
13,D401 (blocoAP),07/07/2022,09/07/2022,"$ 1300,0 reais"
14,D402 (blocoAP),08/06/2022,10/06/2022,"$ 1700,0 reais"
15,D402 (blocoAP),08/07/2022,14/07/2022,"$ 1400,0 reais"
16,E501 (blocoAP),09/06/2022,10/06/2022,"$ 1800,0 reais"
17,E501 (blocoAP),09/07/2022,09/07/2022,"$ 1500,0 reais"
18,E502 (blocoAP),10/06/2022,16/06/2022,"$ 1900,0 reais"
19,E502 (blocoAP),10/07/2022,12/07/2022,"$ 1600,0 reais"
20,F601 (blocoAP),11/06/2022,17/06/2022,"$ 2000,0 reais"
21,F601 (blocoAP),11/07/2022,13/07/2022,"$ 1000,0 reais"
22,F602 (blocoAP),12/06/2022,15/06/2022,"$ 2100,0 reais"
23,F602 (blocoAP),12/07/2022,12/07/2022,"$ 1100,0 reais"
24,G701 (blocoAP),13/06/2022,19/06/2022,"$ 2200,0 reais"
25,G701 (blocoAP),13/07/2022,20/07/2022,"$ 1200,0 reais"
26,G702 (blocoAP),14/06/2022,15/06/2022,"$ 2300,0 reais"
27,G702 (blocoAP),14/07/2022,17/07/2022,"$ 2100,0 reais"
28,H801 (blocoAP),15/06/2022,18/06/2022,"$ 2400,0 reais"
29,H801 (blocoAP),15/07/2022,16/07/2022,"$ 2200,0 reais"

In [ ]:
# Verificar os tipos de dados com info
dados2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     object
dtypes: object(4)
memory usage: 1.1+ KB

In [ ]:
# A coluna numérica é a 'valor_aluguel'
dados2['valor_aluguel']

0     $ 1000,0 reais
1     $ 2500,0 reais
2     $ 1100,0 reais
3     $ 2600,0 reais
4     $ 1200,0 reais
5     $ 2700,0 reais
6     $ 1300,0 reais
7     $ 2800,0 reais
8     $ 1400,0 reais
9     $ 2900,0 reais
10    $ 1500,0 reais
11    $ 1200,0 reais
12    $ 1600,0 reais
13    $ 1300,0 reais
14    $ 1700,0 reais
15    $ 1400,0 reais
16    $ 1800,0 reais
17    $ 1500,0 reais
18    $ 1900,0 reais
19    $ 1600,0 reais
20    $ 2000,0 reais
21    $ 1000,0 reais
22    $ 2100,0 reais
23    $ 1100,0 reais
24    $ 2200,0 reais
25    $ 1200,0 reais
26    $ 2300,0 reais
27    $ 2100,0 reais
28    $ 2400,0 reais
29    $ 2200,0 reais
Name: valor_aluguel, dtype: object

In [ ]:
# Remover os textos presentes na base
# Trocar as vírgulas separadoras do decimal por ponto
dados2['valor_aluguel'] = dados2['valor_aluguel'].apply(lambda x: x.replace('$ ', '').replace(' reais', '').replace(',','.').strip())
# Alterar os tipo de dado para float
dados2['valor_aluguel'] = dados2['valor_aluguel'].astype(np.float64)
# Verificar a transformação
dados2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     float64
dtypes: float64(1), object(3)
memory usage: 1.1+ KB

In [ ]:
dados2['valor_aluguel']

0     1000.0
1     2500.0
2     1100.0
3     2600.0
4     1200.0
5     2700.0
6     1300.0
7     2800.0
8     1400.0
9     2900.0
10    1500.0
11    1200.0
12    1600.0
13    1300.0
14    1700.0
15    1400.0
16    1800.0
17    1500.0
18    1900.0
19    1600.0
20    2000.0
21    1000.0
22    2100.0
23    1100.0
24    2200.0
25    1200.0
26    2300.0
27    2100.0
28    2400.0
29    2200.0
Name: valor_aluguel, dtype: float64

In [ ]:
#retirar textos desnecessários
dados2['apartamento'].str.replace(' \(blocoAP\)', '', regex=True)

# Realizar a substituição dos dados na coluna textual
dados2['apartamento'] = dados2['apartamento'].str.replace(' \(blocoAP\)', '', regex=True)
# Visualizar o resultado final
dados2

   apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0         A101                 01/06/2022         05/06/2022         1000.0
1         A101                 01/07/2022         03/07/2022         2500.0
2         A102                 02/06/2022         02/06/2022         1100.0
3         A102                 02/07/2022         06/07/2022         2600.0
4         B201                 03/06/2022         07/06/2022         1200.0
5         B201                 03/07/2022         03/07/2022         2700.0
6         B202                 04/06/2022         07/06/2022         1300.0
7         B202                 04/07/2022         05/07/2022         2800.0
8         C301                 05/06/2022         10/06/2022         1400.0
9         C301                 05/07/2022         09/07/2022         2900.0
10        C302                 06/06/2022         08/06/2022         1500.0
11        C302                 06/07/2022         12/07/2022         1200.0
12        D401                 07/06/2022         07/06/2022         1600.0
13        D401                 07/07/2022         09/07/2022         1300.0
14        D402                 08/06/2022         10/06/2022         1700.0
15        D402                 08/07/2022         14/07/2022         1400.0
16        E501                 09/06/2022         10/06/2022         1800.0
17        E501                 09/07/2022         09/07/2022         1500.0
18        E502                 10/06/2022         16/06/2022         1900.0
19        E502                 10/07/2022         12/07/2022         1600.0
20        F601                 11/06/2022         17/06/2022         2000.0
21        F601                 11/07/2022         13/07/2022         1000.0
22        F602                 12/06/2022         15/06/2022         2100.0
23        F602                 12/07/2022         12/07/2022         1100.0
24        G701                 13/06/2022         19/06/2022         2200.0
25        G701                 13/07/2022         20/07/2022         1200.0
26        G702                 14/06/2022         15/06/2022         2300.0
27        G702                 14/07/2022         17/07/2022         2100.0
28        H801                 15/06/2022         18/06/2022         2400.0
29        H801                 15/07/2022         16/07/2022         2200.0

In [144]:
dados2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     datetime64[ns]
 2   datas_de_pagamento          30 non-null     datetime64[ns]
 3   valor_aluguel               30 non-null     float64
 4   atraso                      30 non-null     int64
dtypes: datetime64[ns](2), float64(1), int64(1), object(1)
memory usage: 1.3+ KB

In [141]:
# Calcular a média de tempo de atraso por apartamentos
media_atraso = dados2.groupby(['apartamento'])['atraso'].mean()

In [142]:
# Visualizar o resultado
media_atraso

apartamento
A101    3.0
A102    2.0
B201    2.0
B202    2.0
C301    4.5
C302    4.0
D401    1.0
D402    4.0
E501    0.5
E502    4.0
F601    4.0
F602    1.5
G701    6.5
G702    2.0
H801    2.0
Name: atraso, dtype: float64

In [145]:
dados2.head()

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel,atraso
0,A101,2022-06-01,2022-06-05,1000.0,4
1,A101,2022-07-01,2022-07-03,2500.0,2
2,A102,2022-06-02,2022-06-02,1100.0,0
3,A102,2022-07-02,2022-07-06,2600.0,4
4,B201,2022-06-03,2022-06-07,1200.0,4

In [146]:
dados2.to_csv('dados_locacao_imoveis_tratados.csv', index=False)

In [147]:
df2 = pd.read_csv('/content/dados_locacao_imoveis_tratados.csv')
df2

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel,atraso
0,A101,2022-06-01,2022-06-05,1000.0,4
1,A101,2022-07-01,2022-07-03,2500.0,2
2,A102,2022-06-02,2022-06-02,1100.0,0
3,A102,2022-07-02,2022-07-06,2600.0,4
4,B201,2022-06-03,2022-06-07,1200.0,4
5,B201,2022-07-03,2022-07-03,2700.0,0
6,B202,2022-06-04,2022-06-07,1300.0,3
7,B202,2022-07-04,2022-07-05,2800.0,1
8,C301,2022-06-05,2022-06-10,1400.0,5
9,C301,2022-07-05,2022-07-09,2900.0,4
10,C302,2022-06-06,2022-06-08,1500.0,2
11,C302,2022-07-06,2022-07-12,1200.0,6
12,D401,2022-06-07,2022-06-07,1600.0,0
13,D401,2022-07-07,2022-07-09,1300.0,2
14,D402,2022-06-08,2022-06-10,1700.0,2
15,D402,2022-07-08,2022-07-14,1400.0,6
16,E501,2022-06-09,2022-06-10,1800.0,1
17,E501,2022-07-09,2022-07-09,1500.0,0
18,E502,2022-06-10,2022-06-16,1900.0,6
19,E502,2022-07-10,2022-07-12,1600.0,2
20,F601,2022-06-11,2022-06-17,2000.0,6
21,F601,2022-07-11,2022-07-13,1000.0,2
22,F602,2022-06-12,2022-06-15,2100.0,3
23,F602,2022-07-12,2022-07-12,1100.0,0
24,G701,2022-06-13,2022-06-19,2200.0,6
25,G701,2022-07-13,2022-07-20,1200.0,7
26,G702,2022-06-14,2022-06-15,2300.0,1
27,G702,2022-07-14,2022-07-17,2100.0,3
28,H801,2022-06-15,2022-06-18,2400.0,3
29,H801,2022-07-15,2022-07-16,2200.0,1

##*Exercício da aula: Tratando números em strings*

In [ ]:
import pandas as pd
import numpy as np

# dados da firma
dados = {
    'cargo': ['Gerencia', 'Coordenação', 'Supervisão', 'Analista', 'Assistente', 'Operação', 'Auxiliar', 'Estágio', 'Assessoria', 'Consultoria'],
    'quantidade': ['2 pessoas', '1 pessoa', '3 pessoas', '4 pessoas', '5 pessoas', '3 pessoas', '2 pessoas', '1 pessoa', '1 pessoa', '1 pessoa'],
    'salario': ['$10.000 reais', '$8.000 reais', '$7.000 reais', '$5.000 reais', '$4.000 reais', '$3.500 reais', '$3.000 reais', '$1.500 reais', '$2.500 reais', '$6.000 reais']
}

# transformando o dicionário em DataFrame
df = pd.DataFrame(dados)

# df é o DataFrame com os dados da firma
df

         cargo quantidade        salario
0     Gerencia  2 pessoas  $10.000 reais
1  Coordenação   1 pessoa   $8.000 reais
2   Supervisão  3 pessoas   $7.000 reais
3     Analista  4 pessoas   $5.000 reais
4   Assistente  5 pessoas   $4.000 reais
5     Operação  3 pessoas   $3.500 reais
6     Auxiliar  2 pessoas   $3.000 reais
7      Estágio   1 pessoa   $1.500 reais
8   Assessoria   1 pessoa   $2.500 reais
9  Consultoria   1 pessoa   $6.000 reais

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   cargo       10 non-null     object
 1   quantidade  10 non-null     object
 2   salario     10 non-null     object
dtypes: object(3)
memory usage: 372.0+ bytes

In [ ]:
df['quantidade'] = df['quantidade'].apply(lambda x: x.replace(' pessoas', '').replace(' pessoa', ''))
df['salario'] = df['salario'].apply(lambda x: x.replace('$', '').replace(' reais', '').replace('.',''))

In [ ]:
df['quantidade'] = df['quantidade'].astype(np.int64)
df['salario'] = df['salario'].astype(np.float64)

In [ ]:
df

         cargo  quantidade  salario
0     Gerencia           2  10000.0
1  Coordenação           1   8000.0
2   Supervisão           3   7000.0
3     Analista           4   5000.0
4   Assistente           5   4000.0
5     Operação           3   3500.0
6     Auxiliar           2   3000.0
7      Estágio           1   1500.0
8   Assessoria           1   2500.0
9  Consultoria           1   6000.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   cargo       10 non-null     object
 1   quantidade  10 non-null     int64
 2   salario     10 non-null     float64
dtypes: float64(1), int64(1), object(1)
memory usage: 372.0+ bytes