<a href="https://colab.research.google.com/github/alra-code/alura-aprendendo-a-fazer-ETL/blob/main/Pandas_transformacao_manipulacao_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Aula 1 - Manipulação de dados**

Fontes: https://cdn3.gnarususercontent.com.br/2928-transformacao-manipulacao-dados/dados_hospedagem.json

  https://cdn3.gnarususercontent.com.br/2928-transformacao-manipulacao-dados/moveis_disponiveis.json

In [ ]:
#importação da biblioteca
import pandas as pd
#importação dos dados
dados = pd.read_json('/content/dados_hospedagem.json')
dados.head()

                                         info_moveis
0  {'avaliacao_geral': '10.0', 'experiencia_local...
1  {'avaliacao_geral': '10.0', 'experiencia_local...
2  {'avaliacao_geral': '10.0', 'experiencia_local...
3  {'avaliacao_geral': '10.0', 'experiencia_local...
4  {'avaliacao_geral': '10.0', 'experiencia_local...

In [ ]:
#normalizando os dados
dados_normalizados = pd.json_normalize(dados['info_moveis'])
dados_normalizados.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,[This clean and comfortable one bedroom sits r...,[Lower Queen Anne is near the Seattle Center (...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[Real Bed, Futon, Futon, Pull-out Sofa, Real B...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$0, $0, $0, $0, $0, $350.00, $350.00, $350.00...","[$0, $0, $0, $20.00, $15.00, $28.00, $35.00, $...","[$110.00, $45.00, $55.00, $52.00, $85.00, $50...."
1,10.0,--,10,[Welcome to the heart of the 'Ballard Brewery ...,"[--, Capital Hill is the heart of Seattle, bor...","[2, 3, 2, 3, 3, 3, 2, 1, 2, 2, 2]","[3, 4, 2, 3, 3, 3, 3, 3, 3, 4, 3]","[5, 6, 8, 3, 3, 5, 4, 5, 6, 7, 4]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$500.00, $300.00, $0, $300.00, $300.00, $360....","[$125.00, $100.00, $85.00, $110.00, $110.00, $...","[$350.00, $300.00, $425.00, $300.00, $285.00, ..."
2,10.0,--,11,[New modern house built in 2013. Spectacular ...,[Upper Queen Anne is a charming neighborhood f...,[4],[5],[7],[Real Bed],"[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$1,000.00]",[$300.00],[$975.00]
3,10.0,--,12,[Our NW style home is 3200+ sq ft with 3 level...,[The Views from our top floor! Wallingford ha...,"[3, 3, 3, 3, 3, 3, 3, 3]","[6, 6, 5, 5, 5, 5, 4, 4]","[6, 6, 7, 8, 7, 7, 6, 6]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$500.00, $500.00, $500.00, $500.00, $500.00, ...","[$225.00, $300.00, $250.00, $250.00, $250.00, ...","[$490.00, $550.00, $350.00, $350.00, $350.00, ..."
4,10.0,--,14,"[Perfect for groups. 2 bedrooms, full bathroom...",[Safeway grocery store within walking distance...,"[2, 3]","[2, 6]","[3, 9]","[Real Bed, Real Bed]","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$300.00, $2,000.00]","[$40.00, $150.00]","[$200.00, $545.00]"

In [ ]:
#visualizando as colunas
colunas = list(dados_normalizados.columns)
colunas

['avaliacao_geral',
 'experiencia_local',
 'max_hospedes',
 'descricao_local',
 'descricao_vizinhanca',
 'quantidade_banheiros',
 'quantidade_quartos',
 'quantidade_camas',
 'modelo_cama',
 'comodidades',
 'taxa_deposito',
 'taxa_limpeza',
 'preco']

In [ ]:
#retirando as listas
dados_normalizados = dados_normalizados.explode(colunas[3:])
dados_normalizados.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
0,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
0,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00
0,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,$52.00
0,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,$85.00

In [ ]:
#retirando o indesx
dados_normalizados = dados_normalizados.reset_index(drop=True)
dados_normalizados.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
1,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
2,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00
3,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,$52.00
4,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,$85.00

In [ ]:
#verificando os dados
dados_normalizados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3818 non-null   object
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   object
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   object
 6   quantidade_quartos    3818 non-null   object
 7   quantidade_camas      3818 non-null   object
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   object
 11  taxa_limpeza          3818 non-null   object
 12  preco                 3818 non-null   object
dtypes: object(13)
memory usage: 387.9+ KB

In [ ]:
#Convertendo os dados numéricos

#importação do numpy
import numpy as np

#trocando o nome do dataframe
dados = dados_normalizados

In [ ]:
#atribuindo type int a coluna 'max_hospede'
dados['max_hospedes']= dados['max_hospedes'].astype(np.int64)

In [ ]:
#conferindo o type das colunas
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3818 non-null   object
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   object
 6   quantidade_quartos    3818 non-null   object
 7   quantidade_camas      3818 non-null   object
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   object
 11  taxa_limpeza          3818 non-null   object
 12  preco                 3818 non-null   object
dtypes: int64(1), object(12)
memory usage: 387.9+ KB

In [ ]:
#Criando variavel para as colunas
col_numericas = ['quantidade_banheiros', 'quantidade_quartos', 'quantidade_camas']

In [ ]:
#alterando o tipe do objeto das colunas
dados[col_numericas] = dados[col_numericas].astype(np.int64)

In [ ]:
#conferindo
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   object
 11  taxa_limpeza          3818 non-null   object
 12  preco                 3818 non-null   float64
dtypes: float64(2), int64(4), object(7)
memory usage: 387.9+ KB

In [ ]:
#alterando a coluna avaliação geral com o metodo astype
dados['avaliacao_geral'] = dados['avaliacao_geral'].astype(np.float64)

In [ ]:
#verificando
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   object
 11  taxa_limpeza          3818 non-null   object
 12  preco                 3818 non-null   object
dtypes: float64(1), int64(4), object(8)
memory usage: 387.9+ KB

In [ ]:
#Tratando da coluna preços
dados['preco']

0       110.0
1        45.0
2        55.0
3        52.0
4        85.0
        ...
3813    299.0
3814    199.0
3815    400.0
3816    250.0
3817    350.0
Name: preco, Length: 3818, dtype: float64

In [ ]:
#Substitundo o $ e a ',' por nada
dados['preco'].apply(lambda x: str(x).replace('$', '').replace(',', '').strip())

0       110.0
1        45.0
2        55.0
3        52.0
4        85.0
        ...
3813    299.0
3814    199.0
3815    400.0
3816    250.0
3817    350.0
Name: preco, Length: 3818, dtype: object

In [ ]:
#atribuindo as alterações ao dataframe
dados['preco'] = dados['preco'].apply(lambda x: str(x).replace('$', '').replace(',', '').strip())

In [ ]:
# alterando o tipo do dado
dados['preco'] =dados['preco'].astype(np.float64)

In [ ]:
#verificando o tipo dos dados
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   object
 11  taxa_limpeza          3818 non-null   object
 12  preco                 3818 non-null   float64
dtypes: float64(2), int64(4), object(7)
memory usage: 387.9+ KB

In [ ]:
#verificando o dataframe
dados.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,110.0
1,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,45.0
2,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,55.0
3,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,52.0
4,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,85.0

In [ ]:
#visualizando colunas especificas do dataframe
dados[['taxa_deposito','taxa_limpeza']]

     taxa_deposito taxa_limpeza
0               $0           $0
1               $0           $0
2               $0           $0
3               $0       $20.00
4               $0       $15.00
...            ...          ...
3813     $1,000.00      $178.00
3814            $0       $99.00
3815            $0           $0
3816     $1,000.00      $150.00
3817       $500.00           $0

[3818 rows x 2 columns]

In [ ]:
#Retirando as strings
dados[['taxa_deposito','taxa_limpeza']].applymap(lambda x: str(x).replace('$', '').replace(',', '').strip())

<ipython-input-60-4328a5360ae5>:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  dados[['taxa_deposito','taxa_limpeza']].applymap(lambda x: str(x).replace('$', '').replace(',', '').strip())

     taxa_deposito taxa_limpeza
0                0            0
1                0            0
2                0            0
3                0        20.00
4                0        15.00
...            ...          ...
3813       1000.00       178.00
3814             0        99.00
3815             0            0
3816       1000.00       150.00
3817        500.00            0

[3818 rows x 2 columns]

In [ ]:
#atribuindo ao dataframe as alteranções
dados[['taxa_deposito','taxa_limpeza']] = dados[['taxa_deposito','taxa_limpeza']].applymap(lambda x: str(x).replace('$', '').replace(',', '').strip())

<ipython-input-61-a6c24810487c>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  dados[['taxa_deposito','taxa_limpeza']] = dados[['taxa_deposito','taxa_limpeza']].applymap(lambda x: str(x).replace('$', '').replace(',', '').strip())

In [ ]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   object
 11  taxa_limpeza          3818 non-null   object
 12  preco                 3818 non-null   float64
dtypes: float64(2), int64(4), object(7)
memory usage: 387.9+ KB

In [ ]:
#transformando em float os dados e atribuindo ao dataframe
dados[['taxa_deposito','taxa_limpeza']] = dados[['taxa_deposito','taxa_limpeza']].astype(np.float64)

In [ ]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   float64
 11  taxa_limpeza          3818 non-null   float64
 12  preco                 3818 non-null   float64
dtypes: float64(4), int64(4), object(5)
memory usage: 387.9+ KB

In [ ]:
#manipulação dos textos
dados['descricao_local']

0       This clean and comfortable one bedroom sits ri...
1       Our century old Upper Queen Anne house is loca...
2       Cozy room in two-bedroom apartment along the l...
3       Very lovely and cozy room for one. Convenientl...
4       The “Studio at Mibbett Hollow' is in a Beautif...
                              ...
3813    Beautiful craftsman home in the historic Wedgw...
3814    Located in a very easily accessible area of Se...
3815    This home is fully furnished and available wee...
3816    This business-themed modern home features:  *H...
3817    This welcoming home is in the quiet residentia...
Name: descricao_local, Length: 3818, dtype: object

In [ ]:
#atribuindo letras minusculas
dados['descricao_local']=dados['descricao_local'].str.lower()

In [ ]:
dados['descricao_local'].head()

0    this clean and comfortable one bedroom sits ri...
1    our century old upper queen anne house is loca...
2    cozy room in two-bedroom apartment along the l...
3    very lovely and cozy room for one. convenientl...
4    the “studio at mibbett hollow' is in a beautif...
Name: descricao_local, dtype: object

In [ ]:
#Removendo carateres que não trazem informação
dados['descricao_local'][3169]

"built, run and supported by seattle tech and start up veterans, grokhome's focus is to create a supportive environment for smart people working on interesting projects, start ups and more. this listing is an upper bunk, in a 2-person shared room. *note: this fall, there will be major renovations happening on one kitchen and bathroom at a time. there will always be two other working kitchens and two working bathrooms in the house. we'll work to minimize the impact these renovations have on your stay. **this listing is only available to those working in the tech/science space. live in a hacker house, and immerse yourself in the seattle tech scene. you can expect to be surrounded by smart people solving big problems or working on something fun. we have frequent demo nights, and love when our guests share something they are passionate about. if you're new to the city, our deep ties to the seattle tech scene can help you get involved. expand your network, develop your ideas, and learn somet"

In [ ]:
dados['descricao_local'].str.replace('[^a-zA-Z0-9\-\']',' ',regex=True)

0       this clean and comfortable one bedroom sits ri...
1       our century old upper queen anne house is loca...
2       cozy room in two-bedroom apartment along the l...
3       very lovely and cozy room for one  convenientl...
4       the  studio at mibbett hollow' is in a beautif...
                              ...
3813    beautiful craftsman home in the historic wedgw...
3814    located in a very easily accessible area of se...
3815    this home is fully furnished and available wee...
3816    this business-themed modern home features    h...
3817    this welcoming home is in the quiet residentia...
Name: descricao_local, Length: 3818, dtype: object

In [ ]:
#atribuindo o resultado a coluna descrição local
dados['descricao_local'] = dados['descricao_local'].str.replace('[^a-zA-Z0-9\-\']',' ',regex=True)

In [ ]:
#verificando os caracteres
dados['descricao_local'].str.replace('(?<!\w)-(?!\w)',' ',regex=True)

0       this clean and comfortable one bedroom sits ri...
1       our century old upper queen anne house is loca...
2       cozy room in two-bedroom apartment along the l...
3       very lovely and cozy room for one  convenientl...
4       the  studio at mibbett hollow' is in a beautif...
                              ...
3813    beautiful craftsman home in the historic wedgw...
3814    located in a very easily accessible area of se...
3815    this home is fully furnished and available wee...
3816    this business-themed modern home features    h...
3817    this welcoming home is in the quiet residentia...
Name: descricao_local, Length: 3818, dtype: object

In [ ]:
#atribuindo o resultado a coluna descrição local
dados['descricao_local'] = dados['descricao_local'].str.replace('(?<!\w)-(?!\w)',' ',regex=True)

In [ ]:
#Transformando o str em lista
dados['descricao_local'].str.split()

0       [this, clean, and, comfortable, one, bedroom, ...
1       [our, century, old, upper, queen, anne, house,...
2       [cozy, room, in, two-bedroom, apartment, along...
3       [very, lovely, and, cozy, room, for, one, conv...
4       [the, studio, at, mibbett, hollow', is, in, a,...
                              ...
3813    [beautiful, craftsman, home, in, the, historic...
3814    [located, in, a, very, easily, accessible, are...
3815    [this, home, is, fully, furnished, and, availa...
3816    [this, business-themed, modern, home, features...
3817    [this, welcoming, home, is, in, the, quiet, re...
Name: descricao_local, Length: 3818, dtype: object

In [ ]:
#Atrubuindo o resultado a coluna
dados['descricao_local'] = dados['descricao_local'].str.split()

In [ ]:
dados.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,"[this, clean, and, comfortable, one, bedroom, ...",Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",0.0,0.0,110.0
1,10.0,--,1,"[our, century, old, upper, queen, anne, house,...","Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",0.0,0.0,45.0
2,10.0,--,1,"[cozy, room, in, two-bedroom, apartment, along...",The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",0.0,0.0,55.0
3,10.0,--,1,"[very, lovely, and, cozy, room, for, one, conv...","Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",0.0,20.0,52.0
4,10.0,--,1,"[the, studio, at, mibbett, hollow', is, in, a,...",--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",0.0,15.0,85.0

In [ ]:
#Tratando a coluna comodidades
dados['comodidades'].str.replace('\{|}|\"','',regex=True)

0       Internet,Wireless Internet,Kitchen,Free Parkin...
1       TV,Internet,Wireless Internet,Kitchen,Free Par...
2       TV,Internet,Wireless Internet,Kitchen,Free Par...
3       Internet,Wireless Internet,Kitchen,Free Parkin...
4       Wireless Internet,Kitchen,Free Parking on Prem...
                              ...
3813    TV,Cable TV,Internet,Wireless Internet,Air Con...
3814    TV,Cable TV,Internet,Wireless Internet,Kitchen...
3815    TV,Cable TV,Internet,Wireless Internet,Air Con...
3816    TV,Cable TV,Internet,Wireless Internet,Air Con...
3817    TV,Internet,Wireless Internet,Kitchen,Free Par...
Name: comodidades, Length: 3818, dtype: object

In [ ]:
#atribuindo o resultado a coluna comodidades
dados['comodidades'] = dados['comodidades'].str.replace('\{|}|\"','',regex=True)

In [ ]:
#colocando o separador (,)
dados['comodidades'] = dados['comodidades'].str.split(',')

In [ ]:
#visualizar o resultado
dados['comodidades'].head()

0    [Internet, Wireless Internet, Kitchen, Free Pa...
1    [TV, Internet, Wireless Internet, Kitchen, Fre...
2    [TV, Internet, Wireless Internet, Kitchen, Fre...
3    [Internet, Wireless Internet, Kitchen, Free Pa...
4    [Wireless Internet, Kitchen, Free Parking on P...
Name: comodidades, dtype: object

In [ ]:
  # Transformamos o texto em letras minúsculas
dados['descricao_vizinhanca'] = dados['descricao_vizinhanca'].str.lower()
# Substituimos os caractere especiais
dados['descricao_vizinhanca'] = dados['descricao_vizinhanca'].str.replace('[^a-zA-Z0-9\-\']', ' ', regex=True)
dados['descricao_vizinhanca'] = dados['descricao_vizinhanca'].str.replace('(?<!\w)-(?!\w)', '', regex=True)
# Transformamos o texto em lista, formando o token
dados['descricao_vizinhanca'] = dados['descricao_vizinhanca'].str.split()
dados.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,"[this, clean, and, comfortable, one, bedroom, ...","[lower, queen, anne, is, near, the, seattle, c...",1,1,1,Real Bed,"[Internet, Wireless Internet, Kitchen, Free Pa...",0.0,0.0,110.0
1,10.0,--,1,"[our, century, old, upper, queen, anne, house,...","[upper, queen, anne, is, a, really, pleasant, ...",1,1,1,Futon,"[TV, Internet, Wireless Internet, Kitchen, Fre...",0.0,0.0,45.0
2,10.0,--,1,"[cozy, room, in, two-bedroom, apartment, along...","[the, convenience, of, being, in, seattle, but...",1,1,1,Futon,"[TV, Internet, Wireless Internet, Kitchen, Fre...",0.0,0.0,55.0
3,10.0,--,1,"[very, lovely, and, cozy, room, for, one, conv...","[ballard, is, lovely, vibrant, and, one, of, t...",1,1,1,Pull-out Sofa,"[Internet, Wireless Internet, Kitchen, Free Pa...",0.0,20.0,52.0
4,10.0,--,1,"[the, studio, at, mibbett, hollow', is, in, a,...",[],1,1,1,Real Bed,"[Wireless Internet, Kitchen, Free Parking on P...",0.0,15.0,85.0

In [ ]:
#lendo e transformando em dataframe
dt_data = pd.read_json('/content/moveis_disponiveis.json')
dt_data.head()

    id        data  vaga_disponivel preco
0  857  2016-01-04            False  None
1  857  2016-01-05            False  None
2  857  2016-01-06            False  None
3  857  2016-01-07            False  None
4  857  2016-01-08            False  None

In [ ]:
dt_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               365000 non-null  int64
 1   data             365000 non-null  object
 2   vaga_disponivel  365000 non-null  bool
 3   preco            270547 non-null  object
dtypes: bool(1), int64(1), object(2)
memory usage: 11.5+ MB

In [ ]:
#transformando o tipo object para datatime e atribuindo o resultaddo ao dataframe
dt_data['data'] = pd.to_datetime(dt_data['data'])

In [ ]:
dt_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               365000 non-null  int64
 1   data             365000 non-null  datetime64[ns]
 2   vaga_disponivel  365000 non-null  bool
 3   preco            270547 non-null  object
dtypes: bool(1), datetime64[ns](1), int64(1), object(1)
memory usage: 11.5+ MB

In [ ]:
#manipulando dados temporais
dt_data.head()

    id       data  vaga_disponivel preco
0  857 2016-01-04            False  None
1  857 2016-01-05            False  None
2  857 2016-01-06            False  None
3  857 2016-01-07            False  None
4  857 2016-01-08            False  None

In [ ]:
dt_data['data'].dt.strftime('%Y-%m')

0         2016-01
1         2016-01
2         2016-01
3         2016-01
4         2016-01
           ...
364995    2016-12
364996    2016-12
364997    2016-12
364998    2017-01
364999    2017-01
Name: data, Length: 365000, dtype: object

In [ ]:
subset = dt_data.groupby(dt_data['data'].dt.strftime('%Y-%m'))['vaga_disponivel'].sum()
subset

data
2016-01    16543
2016-02    20128
2016-03    23357
2016-04    22597
2016-05    23842
2016-06    23651
2016-07    22329
2016-08    22529
2016-09    22471
2016-10    23765
2016-11    23352
2016-12    24409
2017-01     1574
Name: vaga_disponivel, dtype: int64

In [ ]:
#Tratando a coluna preço
#substituindo valores nulos por 0
dt_data['preco'].fillna('0.0', inplace = True)

In [ ]:
# apagando o $ e as vírgulas com apply lambda
dt_data['preco'] = dt_data['preco'].apply(lambda x: x.replace('$', '').replace(',',''))

In [ ]:
# transformando os tipos de dados para float64
dt_data['preco'] = dt_data['preco'].astype(np.float64)

In [ ]:
# resultado final
dt_data

          id       data  vaga_disponivel  preco
0        857 2016-01-04            False    0.0
1        857 2016-01-05            False    0.0
2        857 2016-01-06            False    0.0
3        857 2016-01-07            False    0.0
4        857 2016-01-08            False    0.0
...      ...        ...              ...    ...
364995  3279 2016-12-29             True  140.0
364996  3279 2016-12-30             True  140.0
364997  3279 2016-12-31             True  140.0
364998  3279 2017-01-01             True  140.0
364999  3279 2017-01-02            False    0.0

[365000 rows x 4 columns]

In [ ]:
dt_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               365000 non-null  int64
 1   data             365000 non-null  datetime64[ns]
 2   vaga_disponivel  365000 non-null  bool
 3   preco            365000 non-null  float64
dtypes: bool(1), datetime64[ns](1), float64(1), int64(1)
memory usage: 11.5 MB